[package]
name = "tokio-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.61"
tokio = { version = "1.26" , features = ["full"]}
mio = "0.8.6"
futures = "0.3"